name: Build Dev Images

on:
  pull_request:
    branches:
      - dev

env:
  PRODUCT_VERSION: "latest"
  AWS_REGION: "us-east-2"
  AMI_FILTER: "ami-0858136e05d24c9c8"
  AMI_PREFIX: "rhel-9-base"
  AMI_SUBNET_ID: "subnet-07b548e510fbc6e00"
  AMI_VPC_ID: "vpc-0e3737a7d61892856"
  OS_VERSION: "Red Hat Enterprise Linux 9"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build RHEL9 AMI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ansible roles
        run: |
          ansible-galaxy install RedHatOfficial.rhel9_cis
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: rhel9_aws_base.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: rhel9_aws_base.pkr.hcl
        env:
          PACKER_LOG: 1