name: Build Dev Images

on:
  pull_request:
    branches:
      - dev

env:
  PRODUCT_VERSION: "latest"
  AWS_REGION: "us-east-2"
  AMI_FILTER: ${{ secrets.AMI_FILTER }}
  AMI_PREFIX: "rhel-9-base"
  AMI_SUBNET_ID: ${{ secrets.AMI_SUBNET_ID }}
  AMI_VPC_ID: ${{ secrets.AMI_VPC_ID }}
  OS_VERSION: "Red Hat Enterprise Linux 9"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build RHEL9 AMI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packer dependencies
        run: |
          pip install -r requirements.txt
          curl -k https://releases.hashicorp.com/packer/1.8.7/packer_1.8.7_linux_amd64.zip --output packer.zip
          unzip packer.zip && mv -f packer /usr/local/bin

      - name: Install ansible roles
        run: |
          ansible-galaxy install RedHatOfficial.rhel9_cis
          sed -i '/socket_file_exists.stdout_lines/d' /home/runner/.ansible/roles/RedHatOfficial.rhel9_cis/tasks/main.yml
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Run `packer init`
        id: init
        run: packer init ./rhel9_aws_base.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: packer validate ./rhel9_aws_base.pkr.hcl

      - name: Build Artifact
        run: packer build -on-error=abort -var "aws_region=${{ env.AWS_REGION }}" -var "ami_filter=${{ env.AMI_FILTER }}" -var "ami_subnet_id=${{ env.AMI_SUBNET_ID }}" -var "ami_vpc_id=${{ env.AMI_VPC_ID }}" ./rhel9_aws_base.pkr.hcl