name: Build Dev Images

on:
  pull_request:
    branches:
      - dev

env:
  PRODUCT_VERSION: "1.6.0"
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: "us-east-2"
  AMI_FILTER: "amazon/RHEL_HA-9.2.0_HVM-*-x86_64-41-Hourly2-GP2"
  AMI_PREFIX: "rhel-9-base"
  OS_VERSION: "Red Hat Enterprise Linux 9"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packer dependencies
        run: |
          pip install -r requirements.txt
          curl -k https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip --output packer.zip
          unzip packer.zip && mv -f packer /usr/local/bin

      - name: Install ansible roles
        run: |
          ansible-galaxy install RedHatOfficial.rhel9_cis

      # - name: Run `packer init`
      #   id: init
      #   # run: "packer init ./rhel9_aws_base.json"

      # - name: Run `packer validate`
      #   id: validate
      #   run: "packer validate ./rhel9_aws_base.json"

      - name: Build Artifact
        run: packer build -on-error=abort ./rhel9_aws_base.json